# generated by datamodel-codegen:
#   filename:  Skatteetaten_FREG-Offentlig-med-hjemmel-1.5-resolved.yaml
#   timestamp: 2022-08-25T13:54:22+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class ErrorMessageForExternalUsers(BaseModel):
    code: Optional[str] = None
    feilreferanse: Optional[str] = None
    http_status: Optional[int] = Field(None, alias='httpStatus')
    message: Optional[str] = None
