# generated by datamodel-codegen:
#   filename:  Skatteetaten_FREG-Offentlig-med-hjemmel-1.5-resolved.yaml
#   timestamp: 2022-08-25T13:54:22+00:00

from __future__ import annotations

from typing import Dict, Optional

from pydantic import BaseModel, Field


class FolkeregisterFeilmelding(BaseModel):
    alvorlighetsgrad: Optional[str] = None
    feilkode: Optional[str] = None
    feilmelding: Optional[str] = None
    http_status: Optional[int] = Field(None, alias='httpStatus')
    tilleggsinformasjon: Optional[Dict[str, str]] = None
