'''
Codes used in matrikkel-client
'''
LAWN_BUILDING_CODES = {
    'ENEBOLIG': '111',
    'ENEBOLIG_MED_HYBEL': '112',
    'VAANINGSHUS':  '113',
    'TOMANNSBOLIG_VERTIKALDELT': '121',
    'TOMANNSBOLIG_HORISONTALDELT': '122',
    'VAANINSHUS_VERTIKALDELT': '123',
    'VAANINSHUS_HORISONTALDELT': '124',
    'REKKEHUS': '131',
    'KJEDE_ATRIUMHUS': '133',
    'TERRASSEHUS': '135',
    'ANDRE_SMAAHUS': '136'
}

ENEBOLIG_BUILDING_TYPE_CODES = {
    'ENEBOLIG': '111',
    'ENEBOLIG_MED_HYBEL': '112',
    'VAANINGSHUS':  '113'
}

TOMANNSBOLIG_BUILDING__TYPE_CODES = {
    'TOMANNSBOLIG_VERTIKALDELT': '121',
    'TOMANNSBOLIG_HORISONTALDELT': '122',
    'VAANINSHUS_VERTIKALDELT': '123',
    'VAANINSHUS_HORISONTALDELT': '124'

}

REKKEHUS_BUILDING_TYPE_CODES = {
    'REKKEHUS': '131',
    'KJEDE_ATRIUMHUS': '133',
    'TERRASSEHUS': '135',
    'ANDRE_SMAAHUS': '136'
}

FRITIDS_BUILDING_TYPE_CODES = {
    'HYTTER_SOMMERHUS_FRITIDSBYGG': '161',
    'HELAARSBOLIG_SOM_FRITIDSBOLIG': '162',
    'VAANINGSHUS_SOM_FRITIDSBOLIG': '163',
}

BUILDING_STATUS_CODES = {'TATT_I_BRUK': 'TB', 'FERDIGATTEST': 'FA', 'MIDLERTIDIG_BRUKSTILLATELSE': 'MB'}
