# generated by datamodel-codegen:
#   filename:  Skatteetaten_FREG-Offentlig-med-hjemmel-1.5-resolved.yaml
#   timestamp: 2022-08-25T13:54:22+00:00

from __future__ import annotations

from datetime import date, datetime
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class Adressenummer(BaseModel):
    husbokstav: Optional[str] = None
    husnummer: str


class Bibeholdstatus(Enum):
    har_bibehold = 'harBibehold'
    har_ikke_lenger_bibehold = 'harIkkeLengerBibehold'
    norsk_statsborger_trenger_ikke_bibehold = 'norskStatsborgerTrengerIkkeBibehold'


class BibeholdAvNorskStatsborgerskap(BaseModel):
    aarsak: Optional[str] = None
    ajourholdstidspunkt: Optional[datetime] = None
    bibeholdstatus: Bibeholdstatus = Field(..., title='Bibehold')
    dato_for_bibehold: Optional[date] = Field(None, alias='datoForBibehold')
    gyldighetstidspunkt: Optional[datetime] = None
    kilde: Optional[str] = None
    opphoerstidspunkt: Optional[datetime] = None


class Adressegradering(Enum):
    ugradert = 'ugradert'
    klientadresse = 'klientadresse'
    fortrolig = 'fortrolig'
    strengt_fortrolig = 'strengtFortrolig'


class AdressegraderingModel(Enum):
    ugradert = 'ugradert'
    klientadresse = 'klientadresse'
    fortrolig = 'fortrolig'
    strengt_fortrolig = 'strengtFortrolig'


class Doedsfall(BaseModel):
    aarsak: Optional[str] = None
    ajourholdstidspunkt: Optional[datetime] = None
    doedsdato: Optional[date] = None
    gyldighetstidspunkt: Optional[datetime] = None
    kilde: Optional[str] = None
    opphoerstidspunkt: Optional[datetime] = None


class MinRolleForPerson(Enum):
    mor = 'mor'
    far = 'far'
    medmor = 'medmor'
    barn = 'barn'
    soesken = 'soesken'
    ektefelle_eller_partner = 'ektefelleEllerPartner'
    doedfoedt_barn = 'doedfoedtBarn'


class RelatertPersonsRolle(Enum):
    mor = 'mor'
    far = 'far'
    medmor = 'medmor'
    barn = 'barn'
    soesken = 'soesken'
    ektefelle_eller_partner = 'ektefelleEllerPartner'
    doedfoedt_barn = 'doedfoedtBarn'


class Foedsel(BaseModel):
    aarsak: Optional[str] = None
    ajourholdstidspunkt: Optional[datetime] = None
    foedekommune_i_norge: Optional[str] = Field(None, alias='foedekommuneINorge')
    foedeland: Optional[str] = None
    foedested: Optional[str] = None
    foedselsaar: str
    foedselsdato: Optional[date] = None
    gyldighetstidspunkt: Optional[datetime] = None
    kilde: Optional[str] = None
    opphoerstidspunkt: Optional[datetime] = None


class FoedselINorge(BaseModel):
    aarsak: Optional[str] = None
    ajourholdstidspunkt: Optional[datetime] = None
    foedselsinstitusjonsnavn: Optional[str] = None
    gyldighetstidspunkt: Optional[datetime] = None
    kilde: Optional[str] = None
    opphoerstidspunkt: Optional[datetime] = None
    rekkefoelgenummer: Optional[int] = None


class Identifikatortype(Enum):
    foedselsnummer = 'foedselsnummer'
    d_nummer = 'dNummer'


class Status(Enum):
    i_bruk = 'iBruk'
    opphoert = 'opphoert'


class Folkeregisteridentifikator(BaseModel):
    aarsak: Optional[str] = None
    ajourholdstidspunkt: Optional[datetime] = None
    foedsels_eller_d_nummer: str = Field(..., alias='foedselsEllerDNummer')
    gyldighetstidspunkt: Optional[datetime] = None
    identifikatortype: Identifikatortype = Field(
        ..., title='Folkeregisteridentifikatortype'
    )
    kilde: Optional[str] = None
    opphoerstidspunkt: Optional[datetime] = None
    status: Status = Field(..., title='Identifikatorstatuskode')


class StatusModel(Enum):
    bosatt = 'bosatt'
    utflyttet = 'utflyttet'
    forsvunnet = 'forsvunnet'
    doed = 'doed'
    opphoert = 'opphoert'
    foedselsregistrert = 'foedselsregistrert'
    midlertidig = 'midlertidig'
    inaktiv = 'inaktiv'
    ikke_bosatt = 'ikkeBosatt'
    aktiv = 'aktiv'


class Folkeregisterpersonstatus(BaseModel):
    aarsak: Optional[str] = None
    ajourholdstidspunkt: Optional[datetime] = None
    gyldighetstidspunkt: Optional[datetime] = None
    kilde: Optional[str] = None
    opphoerstidspunkt: Optional[datetime] = None
    status: StatusModel = Field(..., title='Personstatus')


class Ansvar(Enum):
    felles = 'felles'
    mor = 'mor'
    far = 'far'
    medmor = 'medmor'
    andre = 'andre'
    ukjent = 'ukjent'


class FratattRettsligHandleevne(BaseModel):
    aarsak: Optional[str] = None
    ajourholdstidspunkt: Optional[datetime] = None
    gyldighetstidspunkt: Optional[datetime] = None
    kilde: Optional[str] = None
    opphoerstidspunkt: Optional[datetime] = None


class Graderingsnivaa(Enum):
    ugradert = 'ugradert'
    klientadresse = 'klientadresse'
    fortrolig = 'fortrolig'
    strengt_fortrolig = 'strengtFortrolig'


class GraderingAvAdresse(BaseModel):
    aarsak: Optional[str] = None
    ajourholdstidspunkt: Optional[datetime] = None
    graderingsnivaa: Graderingsnivaa = Field(..., title='Adressegradering')
    gyldighetstidspunkt: Optional[datetime] = None
    kilde: Optional[str] = None
    opphoerstidspunkt: Optional[datetime] = None


class Hendelsestype(Enum):
    endring_i_adressebeskyttelse = 'endringIAdressebeskyttelse'
    endring_i_bostedsadresse = 'endringIBostedsadresse'
    endring_i_bostedsadresse_uten_flytting = 'endringIBostedsadresseUtenFlytting'
    endring_i_bruk_av_samisk_spraak = 'endringIBrukAvSamiskSpraak'
    endring_i_delt_bosted = 'endringIDeltBosted'
    endring_i_doedsfall = 'endringIDoedsfall'
    endring_i_falsk_identitet = 'endringIFalskIdentitet'
    endring_i_familierelasjon = 'endringIFamilierelasjon'
    endring_i_foedsel = 'endringIFoedsel'
    endring_i_foedsel_i_norge = 'endringIFoedselINorge'
    endring_i_foreldreansvar = 'endringIForeldreansvar'
    endring_i_fratatt_rettslig_handleevne = 'endringIFratattRettsligHandleevne'
    endring_i_identifikasjonsnummer = 'endringIIdentifikasjonsnummer'
    endring_i_identitetsgrunnlag = 'endringIIdentitetsgrunnlag'
    endring_i_innflytting = 'endringIInnflytting'
    endring_i_kjoenn = 'endringIKjoenn'
    endring_i_kontaktinformasjon = 'endringIKontaktinformasjon'
    endring_i_kontaktopplysninger_for_doedsbo = 'endringIKontaktopplysningerForDoedsbo'
    endring_i_legitimasjonsdokument = 'endringILegitimasjonsdokument'
    endring_i_navn = 'endringINavn'
    endring_i_opphold = 'endringIOpphold'
    endring_i_opphold_paa_svalbard = 'endringIOppholdPaaSvalbard'
    endring_i_oppholdsadresse = 'endringIOppholdsadresse'
    endring_i_person = 'endringIPerson'
    endring_i_sametingets_valgmanntall = 'endringISametingetsValgmanntall'
    endring_i_sivilstand = 'endringISivilstand'
    endring_i_statsborgerskap = 'endringIStatsborgerskap'
    endring_i_status = 'endringIStatus'
    endring_i_utenlandsk_personidentifikasjon = 'endringIUtenlandskPersonidentifikasjon'
    endring_i_utflytting = 'endringIUtflytting'
    endring_i_utlendingsmyndighetenes_identifikasjonsnummer = (
        'endringIUtlendingsmyndighetenesIdentifikasjonsnummer'
    )
    endring_i_vergemaal = 'endringIVergemaal'
    person_er_bosatt = 'personErBosatt'
    person_er_doed = 'personErDoed'
    person_er_endret_ved_splitting = 'personErEndretVedSplitting'
    person_er_gjenopprettet_ved_splitting = 'personErGjenopprettetVedSplitting'
    person_er_oppdatert = 'personErOppdatert'
    person_er_opphoert = 'personErOpphoert'
    person_er_opphoert_som_dublett = 'personErOpphoertSomDublett'
    person_er_opprettet = 'personErOpprettet'
    person_er_reaktivert = 'personErReaktivert'
    person_er_utflyttet = 'personErUtflyttet'
    person_er_viderefoert_som_gjeldende_ved_sammenslaaing = (
        'personErViderefoertSomGjeldendeVedSammenslaaing'
    )


class Kjoenn(Enum):
    kvinne = 'kvinne'
    mann = 'mann'


class Legitimasjonskontroll(Enum):
    ingen_status = 'ingenStatus'
    ikke_kontrollert = 'ikkeKontrollert'
    kontrollert = 'kontrollert'


class Identitetsgrunnlag(BaseModel):
    aarsak: Optional[str] = None
    ajourholdstidspunkt: Optional[datetime] = None
    gyldighetstidspunkt: Optional[datetime] = None
    kilde: Optional[str] = None
    legitimasjonskontroll: Legitimasjonskontroll = Field(
        ..., title='Identitetsgrunnlagstatus'
    )
    opphoerstidspunkt: Optional[datetime] = None


class InnflyttingTilNorge(BaseModel):
    aarsak: Optional[str] = None
    ajourholdstidspunkt: Optional[datetime] = None
    fraflyttingsland: Optional[str] = None
    fraflyttingssted_i_utlandet: Optional[str] = Field(
        None, alias='fraflyttingsstedIUtlandet'
    )
    gyldighetstidspunkt: Optional[datetime] = None
    kilde: Optional[str] = None
    opphoerstidspunkt: Optional[datetime] = None


class InternasjonalAdresse(BaseModel):
    adressenavn: Optional[str] = None
    boenhet: Optional[str] = None
    by_eller_stedsnavn: Optional[str] = Field(None, alias='byEllerStedsnavn')
    bygning: Optional[str] = None
    co_adressenavn: Optional[str] = Field(None, alias='coAdressenavn')
    distriktsnavn: Optional[str] = None
    etasjenummer: Optional[str] = None
    landkode: str
    postboks: Optional[str] = None
    postkode: Optional[str] = None
    region: Optional[str] = None


class InternasjonalAdresseIFrittFormat(BaseModel):
    adresselinje: Optional[List[str]] = None
    by_eller_stedsnavn: Optional[str] = Field(None, alias='byEllerStedsnavn')
    landkode: str
    postkode: Optional[str] = None


class AdressegraderingModel1(Enum):
    ugradert = 'ugradert'
    klientadresse = 'klientadresse'
    fortrolig = 'fortrolig'
    strengt_fortrolig = 'strengtFortrolig'


class KontaktadresseForDoedsbo(BaseModel):
    adresselinje: List[str]
    landkode: Optional[str] = None
    postnummer: str
    poststedsnavn: str


class AdressegraderingModel2(Enum):
    ugradert = 'ugradert'
    klientadresse = 'klientadresse'
    fortrolig = 'fortrolig'
    strengt_fortrolig = 'strengtFortrolig'


class KontaktadresseIUtlandet(BaseModel):
    aarsak: Optional[str] = None
    adressegradering: AdressegraderingModel2 = Field(..., title='Adressegradering')
    ajourholdstidspunkt: Optional[datetime] = None
    gyldighetstidspunkt: Optional[datetime] = None
    kilde: Optional[str] = None
    opphoerstidspunkt: Optional[datetime] = None
    utenlandsk_adresse: Optional[InternasjonalAdresse] = Field(
        None, alias='utenlandskAdresse'
    )
    utenlandsk_adresse_i_fritt_format: Optional[
        InternasjonalAdresseIFrittFormat
    ] = Field(None, alias='utenlandskAdresseIFrittFormat')


class Skifteform(Enum):
    offentlig = 'offentlig'
    annet = 'annet'


class Bruksenhetstype(Enum):
    bolig = 'bolig'
    annet_enn_bolig = 'annetEnnBolig'
    fritidsbolig = 'fritidsbolig'
    ikke_godkjent_bolig = 'ikkeGodkjentBolig'
    unummerert_bruksenhet = 'unummerertBruksenhet'


class Matrikkelnummer(BaseModel):
    bruksnummer: Optional[int] = None
    festenummer: Optional[int] = None
    gaardsnummer: Optional[int] = None
    kommunenummer: str


class Oppholdstillatelse(Enum):
    midlertidig = 'midlertidig'
    permanent = 'permanent'
    opplysning_mangler = 'opplysningMangler'


class Opphold(BaseModel):
    aarsak: Optional[str] = None
    ajourholdstidspunkt: Optional[datetime] = None
    gyldighetstidspunkt: Optional[datetime] = None
    kilde: Optional[str] = None
    opphoerstidspunkt: Optional[datetime] = None
    opphold_fra: Optional[date] = Field(None, alias='oppholdFra')
    opphold_til: Optional[date] = Field(None, alias='oppholdTil')
    oppholdstillatelse: Oppholdstillatelse = Field(..., title='Oppholdstillatelsetype')


class AntattOppholdsvarighet(Enum):
    under_seks_maaneder = 'underSeksMaaneder'
    over_seks_maaneder = 'overSeksMaaneder'
    over_tolv_maaneder = 'overTolvMaaneder'
    ukjent = 'ukjent'


class OppholdPaaSvalbard(BaseModel):
    aarsak: Optional[str] = None
    ajourholdstidspunkt: Optional[datetime] = None
    antall_tidligere_opphold: Optional[int] = Field(
        None, alias='antallTidligereOpphold'
    )
    antatt_oppholdsvarighet: AntattOppholdsvarighet = Field(
        ..., alias='antattOppholdsvarighet', title='OppholdsvarighetType'
    )
    fraflyttingskommunenummer: Optional[str] = None
    fraflyttingsland: Optional[str] = None
    gyldighetstidspunkt: Optional[datetime] = None
    kilde: Optional[str] = None
    opphoerstidspunkt: Optional[datetime] = None
    sluttdato: Optional[date] = None
    startdato: Optional[date] = None


class AdressegraderingModel3(Enum):
    ugradert = 'ugradert'
    klientadresse = 'klientadresse'
    fortrolig = 'fortrolig'
    strengt_fortrolig = 'strengtFortrolig'


class OppholdAnnetSted(Enum):
    militaer = 'militaer'
    utenriks = 'utenriks'
    paa_svalbard = 'paaSvalbard'
    pendler = 'pendler'


class Personidentifikasjon(BaseModel):
    aarsak: Optional[str] = None
    ajourholdstidspunkt: Optional[datetime] = None
    gyldighetstidspunkt: Optional[datetime] = None
    identifikasjonsnummer: str
    identifikasjonsnummertype: str
    kilde: Optional[str] = None
    opphoerstidspunkt: Optional[datetime] = None
    utstederland: str


class KjoennModel(Enum):
    kvinne = 'kvinne'
    mann = 'mann'


class Personkjoenn(BaseModel):
    aarsak: Optional[str] = None
    ajourholdstidspunkt: Optional[datetime] = None
    gyldighetstidspunkt: Optional[datetime] = None
    kilde: Optional[str] = None
    kjoenn: KjoennModel = Field(..., title='Kjoenn')
    opphoerstidspunkt: Optional[datetime] = None


class Personnavn(BaseModel):
    etternavn: str
    fornavn: str
    mellomnavn: Optional[str] = None


class Poststed(BaseModel):
    postnummer: Optional[str] = None
    poststedsnavn: Optional[str] = None


class Entitet(Enum):
    adressebeskyttelse = 'adressebeskyttelse'
    bibehold = 'bibehold'
    bostedsadresse = 'bostedsadresse'
    bruk_av_samisk_spraak = 'brukAvSamiskSpraak'
    delt_bosted = 'deltBosted'
    doedsfall = 'doedsfall'
    falsk_identitet = 'falskIdentitet'
    familierelasjon = 'familierelasjon'
    foedsel = 'foedsel'
    foedsel_i_norge = 'foedselINorge'
    foreldreansvar = 'foreldreansvar'
    forhold_til_sametingets_valgmanntall = 'forholdTilSametingetsValgmanntall'
    fratatt_rettslig_handleevne = 'fratattRettsligHandleevne'
    kontaktinformasjon_for_doedsbo = 'kontaktinformasjonForDoedsbo'
    identifikasjonsnummer = 'identifikasjonsnummer'
    identitetsgrunnlag = 'identitetsgrunnlag'
    innflytting = 'innflytting'
    kjoenn = 'kjoenn'
    kontaktadresse = 'kontaktadresse'
    kontaktadresse_i_utlandet = 'kontaktadresseIUtlandet'
    legitimasjonsdokument = 'legitimasjonsdokument'
    navn = 'navn'
    opphold = 'opphold'
    oppholdsadresse = 'oppholdsadresse'
    sivilstand = 'sivilstand'
    statsborgerskap = 'statsborgerskap'
    status = 'status'
    utenlandsk_personidentifikasjon = 'utenlandskPersonidentifikasjon'
    utflytting = 'utflytting'
    utlendingsmyndighetenes_identifikasjonsnummer = (
        'utlendingsmyndighetenesIdentifikasjonsnummer'
    )
    vergemaal_eller_fremtidsfullmakt = 'vergemaalEllerFremtidsfullmakt'


class Entitetsendring(Enum):
    registrere_ny = 'registrereNy'
    korrigere = 'korrigere'
    annullere = 'annullere'
    korrigere_historisk = 'korrigereHistorisk'


class KjoennModel1(Enum):
    kvinne = 'kvinne'
    mann = 'mann'


class RelatertBiPerson(BaseModel):
    foedselsdato: Optional[date] = None
    kjoenn: Optional[KjoennModel1] = Field(None, title='Kjoenn')
    navn: Personnavn
    statsborgerskap: Optional[str] = None


class Forhold(Enum):
    innmeldt = 'innmeldt'
    utmeldt = 'utmeldt'
    aldri_innmeldt = 'aldriInnmeldt'


class SametingetsValgmanntall(BaseModel):
    aarsak: Optional[str] = None
    ajourholdstidspunkt: Optional[datetime] = None
    forhold: Forhold = Field(..., title='ForholdTilSametingetsValgmanntall')
    gyldighetstidspunkt: Optional[datetime] = None
    kilde: Optional[str] = None
    opphoerstidspunkt: Optional[datetime] = None
    vedtaksdato: date


class SpraakEnum(Enum):
    nordsamisk = 'nordsamisk'
    soersamisk = 'soersamisk'
    lulesamisk = 'lulesamisk'


class SamiskSpraak(BaseModel):
    aarsak: Optional[str] = None
    ajourholdstidspunkt: Optional[datetime] = None
    gyldighetstidspunkt: Optional[datetime] = None
    kilde: Optional[str] = None
    opphoerstidspunkt: Optional[datetime] = None
    spraak: List[SpraakEnum]


class Sivilstand(Enum):
    uoppgitt = 'uoppgitt'
    ugift = 'ugift'
    gift = 'gift'
    enke_eller_enkemann = 'enkeEllerEnkemann'
    skilt = 'skilt'
    separert = 'separert'
    registrert_partner = 'registrertPartner'
    separert_partner = 'separertPartner'
    skilt_partner = 'skiltPartner'
    gjenlevende_partner = 'gjenlevendePartner'


class SivilstandModel(BaseModel):
    aarsak: Optional[str] = None
    ajourholdstidspunkt: Optional[datetime] = None
    gyldighetstidspunkt: Optional[datetime] = None
    kilde: Optional[str] = None
    kommune: Optional[str] = None
    myndighet: Optional[str] = None
    opphoerstidspunkt: Optional[datetime] = None
    relatert_ved_sivilstand: Optional[str] = Field(None, alias='relatertVedSivilstand')
    sivilstand: Sivilstand = Field(..., title='Sivilstandstype')
    sivilstandsdato: Optional[date] = None
    sted: Optional[str] = None
    utland: Optional[str] = None


class Statsborgerskap(BaseModel):
    aarsak: Optional[str] = None
    ajourholdstidspunkt: Optional[datetime] = None
    ervervsdato: Optional[date] = None
    gyldighetstidspunkt: Optional[datetime] = None
    kilde: Optional[str] = None
    opphoerstidspunkt: Optional[datetime] = None
    statsborgerskap: str


class TekniskDokumentkontroll(BaseModel):
    dokumentkontrollstatus: str
    dokumentkontrolltidspunkt: Optional[datetime] = None


class UkjentBosted(BaseModel):
    bostedskommune: Optional[str] = None


class UtflyttingFraNorge(BaseModel):
    aarsak: Optional[str] = None
    ajourholdstidspunkt: Optional[datetime] = None
    gyldighetstidspunkt: Optional[datetime] = None
    kilde: Optional[str] = None
    opphoerstidspunkt: Optional[datetime] = None
    tilflyttingsland: Optional[str] = None
    tilflyttingssted_i_utlandet: Optional[str] = Field(
        None, alias='tilflyttingsstedIUtlandet'
    )
    utflyttingsdato: Optional[date] = None


class BruksenhetstypeModel(Enum):
    bolig = 'bolig'
    annet_enn_bolig = 'annetEnnBolig'
    fritidsbolig = 'fritidsbolig'
    ikke_godkjent_bolig = 'ikkeGodkjentBolig'
    unummerert_bruksenhet = 'unummerertBruksenhet'


class Vegadresse(BaseModel):
    adressekode: Optional[str] = None
    adressenavn: str
    adressenummer: Optional[Adressenummer] = None
    adressetilleggsnavn: Optional[str] = None
    bruksenhetsnummer: Optional[str] = None
    bruksenhetstype: Optional[BruksenhetstypeModel] = Field(
        None, title='Bruksenhetstype'
    )
    co_adressenavn: Optional[str] = Field(None, alias='coAdressenavn')
    kommunenummer: str
    poststed: Optional[Poststed] = None


class VegadresseForPost(BaseModel):
    adressekode: Optional[str] = None
    adressenavn: Optional[str] = None
    adressenummer: Optional[Adressenummer] = None
    adressetilleggsnavn: Optional[str] = None
    bruksenhetsnummer: Optional[str] = None
    co_adressenavn: Optional[str] = Field(None, alias='coAdressenavn')
    poststed: Optional[Poststed] = None


class Omfang(Enum):
    utlendingssaker_personlige_og_oekonomiske_interesser = (
        'utlendingssakerPersonligeOgOekonomiskeInteresser'
    )
    personlige_og_oekonomiske_interesser = 'personligeOgOekonomiskeInteresser'
    oekonomiske_interesser = 'oekonomiskeInteresser'
    personlige_interesser = 'personligeInteresser'


class VergeRepresentantEllerFullmektig(BaseModel):
    foedsels_eller_d_nummer: Optional[str] = Field(None, alias='foedselsEllerDNummer')
    navn: Optional[Personnavn] = None
    omfang: Optional[Omfang] = Field(None, title='Vergemaalsomfang')
    omfanget_er_innen_personlig_omraade: Optional[bool] = Field(
        None, alias='omfangetErInnenPersonligOmraade'
    )


class Vergemaaltype(Enum):
    enslig_mindreaarig_asylsoeker = 'ensligMindreaarigAsylsoeker'
    enslig_mindreaarig_flyktning = 'ensligMindreaarigFlyktning'
    voksen = 'voksen'
    midlertidig_for_voksen = 'midlertidigForVoksen'
    mindreaarig = 'mindreaarig'
    midlertidig_for_mindreaarig = 'midlertidigForMindreaarig'
    forvaltning_utenfor_vergemaal = 'forvaltningUtenforVergemaal'
    stadfestet_fremtidsfullmakt = 'stadfestetFremtidsfullmakt'


class VergemaalRepresentasjonEllerFremtidsfullmakt(BaseModel):
    aarsak: Optional[str] = None
    ajourholdstidspunkt: Optional[datetime] = None
    embete: Optional[str] = None
    gyldighetstidspunkt: Optional[datetime] = None
    kilde: Optional[str] = None
    opphoerstidspunkt: Optional[datetime] = None
    verge: VergeRepresentantEllerFullmektig
    vergemaaltype: Optional[Vergemaaltype] = Field(None, title='Vergemaaltype')


class AdvokatSomKontakt(BaseModel):
    organisasjonsnavn: Optional[str] = None
    organisasjonsnummer: Optional[str] = None
    personnavn: Personnavn


class Familierelasjon(BaseModel):
    aarsak: Optional[str] = None
    ajourholdstidspunkt: Optional[datetime] = None
    gyldighetstidspunkt: Optional[datetime] = None
    kilde: Optional[str] = None
    min_rolle_for_person: Optional[MinRolleForPerson] = Field(
        None, alias='minRolleForPerson', title='Familierelasjontype'
    )
    opphoerstidspunkt: Optional[datetime] = None
    relatert_person: Optional[str] = Field(None, alias='relatertPerson')
    relatert_person_uten_folkeregisteridentifikator: Optional[RelatertBiPerson] = Field(
        None, alias='relatertPersonUtenFolkeregisteridentifikator'
    )
    relatert_persons_rolle: RelatertPersonsRolle = Field(
        ..., alias='relatertPersonsRolle', title='Familierelasjontype'
    )


class Folkeregisterpersonnavn(BaseModel):
    aarsak: Optional[str] = None
    ajourholdstidspunkt: Optional[datetime] = None
    etternavn: str
    forkortet_navn: Optional[str] = Field(None, alias='forkortetNavn')
    fornavn: str
    gyldighetstidspunkt: Optional[datetime] = None
    kilde: Optional[str] = None
    mellomnavn: Optional[str] = None
    opphoerstidspunkt: Optional[datetime] = None
    originalt_navn: Optional[Personnavn] = Field(None, alias='originaltNavn')


class Foreldreansvar(BaseModel):
    aarsak: Optional[str] = None
    ajourholdstidspunkt: Optional[datetime] = None
    ansvar: Ansvar = Field(..., title='Foreldreansvarstype')
    ansvarlig: Optional[str] = None
    ansvarlig_organisasjon: Optional[str] = Field(None, alias='ansvarligOrganisasjon')
    ansvarlig_uten_identifikator: Optional[RelatertBiPerson] = Field(
        None, alias='ansvarligUtenIdentifikator'
    )
    ansvarssubjekt: Optional[str] = None
    ansvarssubjekt_uten_identifikator: Optional[RelatertBiPerson] = Field(
        None, alias='ansvarssubjektUtenIdentifikator'
    )
    gyldighetstidspunkt: Optional[datetime] = None
    kilde: Optional[str] = None
    opphoerstidspunkt: Optional[datetime] = None


class Identifikasjonsdokument(BaseModel):
    aarsak: Optional[str] = None
    ajourholdstidspunkt: Optional[datetime] = None
    dokumentkontroll: Optional[TekniskDokumentkontroll] = None
    gyldig_fra: Optional[date] = Field(None, alias='gyldigFra')
    gyldig_til: Optional[date] = Field(None, alias='gyldigTil')
    gyldighetstidspunkt: Optional[datetime] = None
    identifikasjonsdokumentnummer: Optional[str] = None
    identifikasjonsdokumenttype: str
    kilde: Optional[str] = None
    opphoerstidspunkt: Optional[datetime] = None
    utstederland: str
    utstedernavn: Optional[str] = None


class IdentifiserendeInformasjon(BaseModel):
    foedselsdato: Optional[date] = None
    kjoenn: Optional[Kjoenn] = Field(None, title='Kjoenn')
    personnavn: Personnavn
    statsborgerskap: List[str]


class Matrikkeladresse(BaseModel):
    adressetilleggsnavn: Optional[str] = None
    bruksenhetsnummer: Optional[str] = None
    bruksenhetstype: Optional[Bruksenhetstype] = Field(None, title='Bruksenhetstype')
    co_adressenavn: Optional[str] = Field(None, alias='coAdressenavn')
    matrikkelnummer: Matrikkelnummer
    poststed: Optional[Poststed] = None
    undernummer: Optional[int] = None


class Oppholdsadresse(BaseModel):
    aarsak: Optional[str] = None
    adresse_identifikator_fra_matrikkelen: Optional[str] = Field(
        None, alias='adresseIdentifikatorFraMatrikkelen'
    )
    adressegradering: AdressegraderingModel3 = Field(..., title='Adressegradering')
    adressen_er_ukjent: Optional[bool] = Field(None, alias='adressenErUkjent')
    ajourholdstidspunkt: Optional[datetime] = None
    gyldighetstidspunkt: Optional[datetime] = None
    kilde: Optional[str] = None
    matrikkeladresse: Optional[Matrikkeladresse] = None
    opphoerstidspunkt: Optional[datetime] = None
    opphold_annet_sted: Optional[OppholdAnnetSted] = Field(
        None, alias='oppholdAnnetSted', title='OppholdAnnetSted'
    )
    oppholdsadressedato: Optional[date] = None
    utenlandsk_adresse: Optional[InternasjonalAdresse] = Field(
        None, alias='utenlandskAdresse'
    )
    vegadresse: Optional[Vegadresse] = None


class OrganisasjonSomKontakt(BaseModel):
    kontaktpersonnavn: Optional[Personnavn] = None
    organisasjonsnavn: str
    organisasjonsnummer: Optional[str] = None


class PersonSomKontakt(BaseModel):
    foedsels_eller_d_nummer: Optional[str] = Field(None, alias='foedselsEllerDNummer')
    foedselsdato: Optional[date] = None
    personnavn: Optional[Personnavn] = None


class PostadresseIFrittFormat(BaseModel):
    adresselinje: Optional[List[str]] = None
    poststed: Optional[Poststed] = None


class Postboksadresse(BaseModel):
    postboks: str
    postbokseier: Optional[str] = None
    poststed: Optional[Poststed] = None


class Bostedsadresse(BaseModel):
    aarsak: Optional[str] = None
    adresse_identifikator_fra_matrikkelen: Optional[str] = Field(
        None, alias='adresseIdentifikatorFraMatrikkelen'
    )
    adressegradering: Adressegradering = Field(..., title='Adressegradering')
    ajourholdstidspunkt: Optional[datetime] = None
    flyttedato: Optional[date] = None
    grunnkrets: Optional[int] = None
    gyldighetstidspunkt: Optional[datetime] = None
    kilde: Optional[str] = None
    kirkekrets: Optional[int] = None
    matrikkeladresse: Optional[Matrikkeladresse] = None
    naer_adresse_identifikator_fra_matrikkelen: Optional[str] = Field(
        None, alias='naerAdresseIdentifikatorFraMatrikkelen'
    )
    opphoerstidspunkt: Optional[datetime] = None
    skolekrets: Optional[int] = None
    stemmekrets: Optional[int] = None
    ukjent_bosted: Optional[UkjentBosted] = Field(None, alias='ukjentBosted')
    vegadresse: Optional[Vegadresse] = None


class DeltBosted(BaseModel):
    aarsak: Optional[str] = None
    adresse_identifikator_fra_matrikkelen: Optional[str] = Field(
        None, alias='adresseIdentifikatorFraMatrikkelen'
    )
    adressegradering: AdressegraderingModel = Field(..., title='Adressegradering')
    ajourholdstidspunkt: Optional[datetime] = None
    gyldighetstidspunkt: Optional[datetime] = None
    kilde: Optional[str] = None
    matrikkeladresse: Optional[Matrikkeladresse] = None
    naer_adresse_identifikator_fra_matrikkelen: Optional[str] = Field(
        None, alias='naerAdresseIdentifikatorFraMatrikkelen'
    )
    opphoerstidspunkt: Optional[datetime] = None
    sluttdato_for_kontrakt: Optional[date] = Field(None, alias='sluttdatoForKontrakt')
    startdato_for_kontrakt: date = Field(..., alias='startdatoForKontrakt')
    ukjent_bosted: Optional[UkjentBosted] = Field(None, alias='ukjentBosted')
    vegadresse: Optional[Vegadresse] = None


class FalskIdentitet(BaseModel):
    aarsak: Optional[str] = None
    ajourholdstidspunkt: Optional[datetime] = None
    er_falsk: Optional[bool] = Field(None, alias='erFalsk')
    gyldighetstidspunkt: Optional[datetime] = None
    kilde: Optional[str] = None
    opphoerstidspunkt: Optional[datetime] = None
    rett_identitet_er_ukjent: Optional[bool] = Field(
        None, alias='rettIdentitetErUkjent'
    )
    rett_identitet_ved_identifikasjonsnummer: Optional[str] = Field(
        None, alias='rettIdentitetVedIdentifikasjonsnummer'
    )
    rett_identitet_ved_opplysninger: Optional[IdentifiserendeInformasjon] = Field(
        None, alias='rettIdentitetVedOpplysninger'
    )


class Kontaktadresse(BaseModel):
    aarsak: Optional[str] = None
    adresse_identifikator_fra_matrikkelen: Optional[str] = Field(
        None, alias='adresseIdentifikatorFraMatrikkelen'
    )
    adressegradering: AdressegraderingModel1 = Field(..., title='Adressegradering')
    ajourholdstidspunkt: Optional[datetime] = None
    gyldighetstidspunkt: Optional[datetime] = None
    kilde: Optional[str] = None
    opphoerstidspunkt: Optional[datetime] = None
    postadresse_i_fritt_format: Optional[PostadresseIFrittFormat] = Field(
        None, alias='postadresseIFrittFormat'
    )
    postboksadresse: Optional[Postboksadresse] = None
    vegadresse: Optional[VegadresseForPost] = None


class KontaktinformasjonForDoedsbo(BaseModel):
    aarsak: Optional[str] = None
    adresse: KontaktadresseForDoedsbo
    advokat: Optional[AdvokatSomKontakt] = None
    ajourholdstidspunkt: Optional[datetime] = None
    attestutstedelsesdato: date
    gyldighetstidspunkt: Optional[datetime] = None
    kilde: Optional[str] = None
    opphoerstidspunkt: Optional[datetime] = None
    organisasjon: Optional[OrganisasjonSomKontakt] = None
    person: Optional[PersonSomKontakt] = None
    skifteform: Skifteform = Field(..., title='Skifteform')


class Registerdata(BaseModel):
    adressebeskyttelse: Optional[GraderingAvAdresse] = None
    bibehold: Optional[BibeholdAvNorskStatsborgerskap] = None
    bostedsadresse: Optional[Bostedsadresse] = None
    bruk_av_samisk_spraak: Optional[SamiskSpraak] = Field(
        None, alias='brukAvSamiskSpraak'
    )
    delt_bosted: Optional[DeltBosted] = Field(None, alias='deltBosted')
    doedsfall: Optional[Doedsfall] = None
    entitet: Entitet = Field(..., title='Entitetsnavn')
    entitetsendring: Entitetsendring = Field(..., title='Entitetsendring')
    falsk_identitet: Optional[FalskIdentitet] = Field(None, alias='falskIdentitet')
    familierelasjon: Optional[Familierelasjon] = None
    foedsel: Optional[Foedsel] = None
    foedsel_i_norge: Optional[FoedselINorge] = Field(None, alias='foedselINorge')
    foreldreansvar: Optional[Foreldreansvar] = None
    forhold_til_sametingets_valgmanntall: Optional[SametingetsValgmanntall] = Field(
        None, alias='forholdTilSametingetsValgmanntall'
    )
    fratatt_rettslig_handleevne: Optional[FratattRettsligHandleevne] = Field(
        None, alias='fratattRettsligHandleevne'
    )
    identifikasjonsnummer: Optional[Folkeregisteridentifikator] = None
    identitetsgrunnlag: Optional[Identitetsgrunnlag] = None
    innflytting: Optional[InnflyttingTilNorge] = None
    kjoenn: Optional[Personkjoenn] = None
    kontaktinformasjon_for_doedsbo: Optional[KontaktinformasjonForDoedsbo] = Field(
        None, alias='kontaktinformasjonForDoedsbo'
    )
    legitimasjonsdokument: Optional[Identifikasjonsdokument] = None
    navn: Optional[Folkeregisterpersonnavn] = None
    opphold: Optional[Opphold] = None
    opphold_paa_svalbard: Optional[OppholdPaaSvalbard] = Field(
        None, alias='oppholdPaaSvalbard'
    )
    oppholdsadresse: Optional[Oppholdsadresse] = None
    postadresse: Optional[Kontaktadresse] = None
    postadresse_i_utlandet: Optional[KontaktadresseIUtlandet] = Field(
        None, alias='postadresseIUtlandet'
    )
    sivilstand: Optional[SivilstandModel] = None
    statsborgerskap: Optional[Statsborgerskap] = None
    status: Optional[Folkeregisterpersonstatus] = None
    utenlandsk_personidentifikasjon: Optional[Personidentifikasjon] = Field(
        None, alias='utenlandskPersonidentifikasjon'
    )
    utflytting: Optional[UtflyttingFraNorge] = None
    utlendingsmyndighetenes_identifikasjonsnummer: Optional[
        Personidentifikasjon
    ] = Field(None, alias='utlendingsmyndighetenesIdentifikasjonsnummer')
    vergemaal_eller_fremtidsfullmakt: Optional[
        VergemaalRepresentasjonEllerFremtidsfullmakt
    ] = Field(None, alias='vergemaalEllerFremtidsfullmakt')


class Hendelse(BaseModel):
    ajourholdstidspunkt: datetime
    egenskapshendelse: Optional[List[Registerdata]] = None
    folkeregisteridentifikator: str
    hendelsesaarsak_i_dsf: Optional[str] = Field(None, alias='hendelsesaarsakIDsf')
    hendelsestype: Hendelsestype = Field(..., title='Hendelsestype')


class DokumentForHendelse(BaseModel):
    dokumentidentifikator: str
    hendelse: Hendelse
    skjemaversjon: str
