# pylint: disable-all
# pylint: disable-all
"""Cascade delete
Revision ID: 1e15a13c7111
Revises: f06d4e2a8a37
Create Date: 2020-12-17 16:08:24.963242
"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '1e15a13c7111'
down_revision = 'cbe2957a938e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('message_bulletin_id_fkey', 'message', type_='foreignkey', schema='innbyggerkontakt_outcome')
    op.create_foreign_key('message_bulletin_id_fkey', 'message', 'bulletin', ['bulletin_id'], ['bulletin_id'],
                          ondelete="CASCADE", source_schema='innbyggerkontakt_outcome',
                          referent_schema='innbyggerkontakt_outcome')
    op.drop_constraint("recipients_bulletin_id_fkey", 'recipients', type_="foreignkey",
                       schema='innbyggerkontakt_outcome')
    op.create_foreign_key('recipients_bulletin_id_fkey', 'recipients', 'bulletin', ['bulletin_id'], ['bulletin_id'],
                          ondelete="CASCADE", source_schema='innbyggerkontakt_outcome',
                          referent_schema='innbyggerkontakt_outcome')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('recipients_bulletin_id_fkey', 'recipients', type_='foreignkey',
                       schema='innbyggerkontakt_outcome')
    op.create_foreign_key('recipients_bulletin_id_fkey', 'recipients', 'bulletin', ['bulletin_id'], ['bulletin_id'],
                          source_schema='innbyggerkontakt_outcome', referent_schema='innbyggerkontakt_outcome')
    op.drop_constraint('message_bulletin_id_fkey', 'message', type_='foreignkey', schema='innbyggerkontakt_outcome')
    op.create_foreign_key('message_bulletin_id_fkey', 'message', 'bulletin', ['bulletin_id'], ['bulletin_id'],
                          source_schema='innbyggerkontakt_outcome', referent_schema='innbyggerkontakt_outcome')
    # ### end Alembic commands ###
