# pylint: disable-all
"""Remove user_id

Revision ID: cbe2957a938e
Revises: f06d4e2a8a37
Create Date: 2021-02-04 10:33:20.540290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbe2957a938e'
down_revision = 'f06d4e2a8a37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bulletin', 'user_id', schema='innbyggerkontakt_outcome')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bulletin', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
                  schema='innbyggerkontakt_outcome')
    op.execute("UPDATE innbyggerkontakt_outcome.bulletin SET user_id='null'")
    op.alter_column('bulletin', 'user_id', nullable=False, schema='innbyggerkontakt_outcome')
    # ### end Alembic commands ###
