# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    # Checkers
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
        exclude: '.*settings.json'
      - id: check-merge-conflict
      - id: detect-private-key
      # Fixers
      - id: trailing-whitespace
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: sort-simple-yaml

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args:
          - "--skip-string-normalization"

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        additional_dependencies: [toml]

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.0
    hooks:
      - id: terraform_fmt

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.2
    hooks:
      - id: pycln

  - repo: https://github.com/flakeheaven/flakeheaven
    rev: 3.2.1
    hooks:
      - id: flakeheaven
        additional_dependencies:
          # Fixed branch of cognitive_complexity
          - cognitive-complexity~=1.3.0
          - flake8-bandit~=3.0.0
          - flake8-bugbear~=22.7.1
          - flake8-cognitive-complexity~=0.1.0
          - flake8-comprehensions~=3.10.0
          - flake8-docstrings~=1.6.0
          - flake8-simplify~=0.19.3
          - flake8-quotes~=3.3.1
          - mccabe~=0.6.1
          - pylint~=2.14.5
