# generated by datamodel-codegen:
#   filename:  Skatteetaten_FREG-Offentlig-med-hjemmel-1.5-resolved.yaml
#   timestamp: 2022-08-25T13:54:22+00:00

from __future__ import annotations

from typing import List, Optional

from folkeregisteret.tilgjengeliggjoering.person.v1 import Folkeregisterperson
from pydantic import BaseModel, Field


class Feilmelding(BaseModel):
    feilmelding: str


class Oppslag(BaseModel):
    feilmelding: Optional[Feilmelding] = None
    foedsels_eller_d_nummer: str = Field(..., alias='foedselsEllerDNummer')
    folkeregisterperson: Optional[Folkeregisterperson] = None


class PersonBulkoppslagResponse(BaseModel):
    oppslag: Optional[List[Oppslag]] = None
