# generated by datamodel-codegen:
#   filename:  https://oidc-ver2.difi.no/kontaktinfo-oauth2-server/rest/v2/api-docs
#   timestamp: 2022-09-15T12:04:48+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, List, Optional

from pydantic import BaseModel, Field


class Model(BaseModel):
    __root__: Any


class ContactInfoResource(BaseModel):
    epostadresse: Optional[str] = None
    epostadresse_oppdatert: Optional[str] = None
    epostadresse_sist_verifisert: Optional[str] = None
    mobiltelefonnummer: Optional[str] = None
    mobiltelefonnummer_oppdatert: Optional[str] = None
    mobiltelefonnummer_sist_verifisert: Optional[str] = None


class DigitalPostResource(BaseModel):
    postkasseadresse: Optional[str] = None
    postkasseleverandoeradresse: Optional[str] = None


class HentPersonerRequest(BaseModel):
    personIdentifiersAsString: Optional[str] = None
    personidentifikatorer: Optional[List[str]] = None


class Spraak(Enum):
    en = 'en'
    se = 'se'
    nb = 'nb'
    nn = 'nn'
    __ = '""'


class KontaktinfoCreateOrPatch(BaseModel):
    epostadresse: Optional[str] = Field(
        None, description='Use empty string to delete user preference.'
    )
    mobiltelefonnummer: Optional[str] = Field(
        None, description='Use empty string to delete user preference.'
    )
    personidentifikator: Optional[str] = None
    spraak: Optional[Spraak] = Field(
        None, description='ISO 639-1. Use empty string to delete user preference.'
    )


class Reservasjon(Enum):
    JA = 'JA'
    NEI = 'NEI'


class Status(Enum):
    AKTIV = 'AKTIV'
    SLETTET = 'SLETTET'
    IKKE_REGISTRERT = 'IKKE_REGISTRERT'


class Varslingsstatus(Enum):
    KAN_IKKE_VARSLES = 'KAN_IKKE_VARSLES'
    KAN_VARSLES = 'KAN_VARSLES'


class PersonResource(BaseModel):
    personidentifikator: Optional[str] = None
    reservasjon: Optional[Reservasjon] = None
    status: Optional[Status] = None
    varslingsstatus: Optional[Varslingsstatus] = None
    kontaktinformasjon: Optional[ContactInfoResource] = None
    digital_post: Optional[DigitalPostResource] = None
    sertifikat: Optional[str] = None
    spraak: Optional[str] = None
    spraak_oppdatert: Optional[str] = None


class PrintSertifikatResponse(BaseModel):
    postkasseleverandoerAdresse: Optional[str] = None
    x509Sertifikat: Optional[str] = None


class Links(BaseModel):
    about: Optional[str] = Field(
        None,
        description='Link to read more about the problem.',
        example='https://http.cat/422',
    )


class Spraak1(Enum):
    en = 'en'
    se = 'se'
    nb = 'nb'
    nn = 'nn'
    __ = '""'


class PersonPatchDocument(BaseModel):
    spraak: Spraak1 = Field(
        ..., description='ISO 639-1. Use empty string to delete user preference.'
    )


class Source(BaseModel):
    pointer: Optional[str] = Field(
        None,
        description='JSON-pointer to relevant field in request-body.',
        example='/spraak',
    )


class HentPersonerResponse(BaseModel):
    personer: Optional[List[PersonResource]] = None


class Error(BaseModel):
    id: Optional[str] = None
    status: Optional[str] = Field(None, description='HTTP status code', example=422)
    title: Optional[str] = Field(
        None,
        description='a short, human-readable summary of the problem',
        example='Invalid value',
    )
    detail: Optional[str] = Field(
        None,
        description='a human-readable explanation specific to this occurrence of the problem',
        example='See documentation for list of possible values.',
    )
    source: Optional[Source] = None
    links: Optional[Links] = None


class Errors(BaseModel):
    errors: Optional[List[Error]] = None
