# generated by datamodel-codegen:
#   filename:  Skatteetaten_FREG-Offentlig-med-hjemmel-1.5-resolved.yaml
#   timestamp: 2022-08-25T13:54:22+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class Kommunenummer(BaseModel):
    bostedskommunenummer: Optional[str] = None
    oppholdskommunenummer: Optional[str] = None


class Kjoenn(Enum):
    kvinne = 'kvinne'
    mann = 'mann'


class PersonstatustyperEnum(Enum):
    aktiv = 'aktiv'
    bosatt = 'bosatt'
    utflyttet = 'utflyttet'
    doed = 'doed'
    inaktiv = 'inaktiv'


class Sivilstandstype(Enum):
    uoppgitt = 'uoppgitt'
    ugift = 'ugift'
    gift = 'gift'
    enke_eller_enkemann = 'enkeEllerEnkemann'
    skilt = 'skilt'
    separert = 'separert'
    registrert_partner = 'registrertPartner'
    separert_partner = 'separertPartner'
    skilt_partner = 'skiltPartner'
    gjenlevende_partner = 'gjenlevendePartner'


class TilpassetUttrekkJobbRequest(BaseModel):
    doedsaar_fra_og_med: Optional[str] = Field(None, alias='doedsaarFraOgMed')
    doedsaar_til_og_med: Optional[str] = Field(None, alias='doedsaarTilOgMed')
    foedselsaar_fra_og_med: Optional[str] = Field(None, alias='foedselsaarFraOgMed')
    foedselsaar_til_og_med: Optional[str] = Field(None, alias='foedselsaarTilOgMed')
    kjoenn: Optional[Kjoenn] = Field(None, title='Kjoenn')
    kommunenummer: Optional[Kommunenummer] = None
    personstatustyper: List[PersonstatustyperEnum]
    sivilstandstype: Optional[Sivilstandstype] = Field(None, title='Sivilstandstype')
    statsborgerskap: Optional[str] = None
