# generated by datamodel-codegen:
#   filename:  Skatteetaten_FREG-Offentlig-med-hjemmel-1.5-resolved.yaml
#   timestamp: 2022-08-25T13:54:22+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class UttrekkDataResponse(BaseModel):
    dokumentidentifikator: Optional[List[str]] = None
    feilmelding: Optional[str] = None
    foedsels_eller_d_nummer: Optional[List[str]] = Field(
        None, alias='foedselsEllerDNummer'
    )


class UttrekkJobbResponse(BaseModel):
    feilmelding: Optional[str] = None
    jobb_id: Optional[str] = Field(None, alias='jobbId')
