# generated by datamodel-codegen:
#   filename:  Skatteetaten_FREG-Offentlig-med-hjemmel-1.5-resolved.yaml
#   timestamp: 2022-08-25T13:54:22+00:00

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel


class HendelseMedDokumentIdentifikatorer(BaseModel):
    ajourholdstidspunkt: Optional[datetime] = None
    folkeregisteridentifikator: Optional[str] = None
    hendelsesdokument: Optional[str] = None
    hendelsetype: Optional[str] = None
    persondokument: Optional[str] = None


class LagretHendelseMedDokumentIdentifikatorer(BaseModel):
    hendelse: Optional[HendelseMedDokumentIdentifikatorer] = None
    sekvensnummer: Optional[int] = None


class Sekvensnummer(BaseModel):
    sekvensnummer: Optional[int] = None
