"""Test-data for KRR."""

krr_test_persons = {
    'personer': [
        {
            'personidentifikator': '1048800153',
            'reservasjon': 'NEI',
            'status': 'AKTIV',
            'varslingsstatus': 'KAN_IKKE_VARSLES',
            'kontaktinformasjon': {
                'mobiltelefonnummer_oppdatert': None,
                'mobiltelefonnummer_sist_verifisert': None,
                'mobiltelefonnummer': None,
                'epostadresse_oppdatert': None,
                'epostadresse_sist_verifisert': None,
                'epostadresse': None,
            },
            'spraak': None,
            'spraak_oppdatert': None,
        },
        {
            'personidentifikator': '1066100746',
            'reservasjon': 'NEI',
            'status': 'AKTIV',
            'varslingsstatus': 'KAN_IKKE_VARSLES',
            'kontaktinformasjon': {
                'mobiltelefonnummer_oppdatert': None,
                'mobiltelefonnummer_sist_verifisert': None,
                'mobiltelefonnummer': None,
                'epostadresse_oppdatert': None,
                'epostadresse_sist_verifisert': None,
                'epostadresse': None,
            },
            'spraak': None,
            'spraak_oppdatert': None,
        },
        {
            'personidentifikator': '27129323960',
            'reservasjon': None,
            'status': 'SLETTET',
            'varslingsstatus': 'KAN_IKKE_VARSLES',
            'kontaktinformasjon': {
                'mobiltelefonnummer_oppdatert': None,
                'mobiltelefonnummer_sist_verifisert': None,
                'mobiltelefonnummer': None,
                'epostadresse_oppdatert': None,
                'epostadresse_sist_verifisert': None,
                'epostadresse': None,
            },
            'spraak': None,
            'spraak_oppdatert': None,
        },
        {
            'personidentifikator': '27129323618',
            'reservasjon': None,
            'status': 'SLETTET',
            'varslingsstatus': 'KAN_IKKE_VARSLES',
            'kontaktinformasjon': {
                'mobiltelefonnummer_oppdatert': None,
                'mobiltelefonnummer_sist_verifisert': None,
                'mobiltelefonnummer': None,
                'epostadresse_oppdatert': None,
                'epostadresse_sist_verifisert': None,
                'epostadresse': None,
            },
            'spraak': None,
            'spraak_oppdatert': None,
        },
        {
            'personidentifikator': '27129324592',
            'reservasjon': 'JA',
            'status': 'AKTIV',
            'varslingsstatus': 'KAN_IKKE_VARSLES',
            'kontaktinformasjon': {
                'mobiltelefonnummer_oppdatert': None,
                'mobiltelefonnummer_sist_verifisert': None,
                'mobiltelefonnummer': '+4799999999',
                'epostadresse_oppdatert': None,
                'epostadresse_sist_verifisert': None,
                'epostadresse': '27129324169-test@minid.norge.no',
            },
            'spraak': None,
            'spraak_oppdatert': None,
        },
        {
            'personidentifikator': '27129324401',
            'reservasjon': 'JA',
            'status': 'AKTIV',
            'varslingsstatus': 'KAN_IKKE_VARSLES',
            'kontaktinformasjon': {
                'mobiltelefonnummer_oppdatert': None,
                'mobiltelefonnummer_sist_verifisert': None,
                'mobiltelefonnummer': '+4799999999',
                'epostadresse_oppdatert': None,
                'epostadresse_sist_verifisert': None,
                'epostadresse': '27129324169-test@minid.norge.no',
            },
            'spraak': None,
            'spraak_oppdatert': None,
        },
        {
            'personidentifikator': '27129324169',
            'reservasjon': 'NEI',
            'status': 'AKTIV',
            'varslingsstatus': 'KAN_VARSLES',
            'kontaktinformasjon': {
                'mobiltelefonnummer_oppdatert': '2015-03-11T19: 57: 52.000+01: 00',
                'mobiltelefonnummer_sist_verifisert': '2017-11-07T09: 48: 38.000+01: 00',
                'mobiltelefonnummer': '+4799999999',
                'epostadresse_oppdatert': '2015-03-11T19: 57: 52.000+01: 00',
                'epostadresse_sist_verifisert': '2017-11-07T09: 48: 38.000+01: 00',
                'epostadresse': '27129324169-test@minid.norge.no',
            },
            'spraak': None,
            'spraak_oppdatert': None,
        },
        {
            'personidentifikator': '27129324088',
            'reservasjon': 'NEI',
            'status': 'AKTIV',
            'varslingsstatus': 'KAN_VARSLES',
            'kontaktinformasjon': {
                'mobiltelefonnummer_sist_oppdatert': '2015-03-11T19: 57: 21.000+01: 00',
                'mobiltelefonnummer_sist_verifisert': '2017-11-07T09: 48: 16.000+01: 00',
                'mobiltelefonnummer': '+4799999999',
                'epostadresse_oppdatert': '2015-03-11T19: 57: 21.000+01: 00',
                'epostadresse_sist_verifisert': '2017-11-07T09: 48: 16.000+01: 00',
                'epostadresse': '27129324088-test@minid.norge.no',
            },
            'spraak': None,
            'spraak_oppdatert': None,
        },
        {
            'personidentifikator': '27129323537',
            'reservasjon': 'NEI',
            'status': 'AKTIV',
            'varslingsstatus': 'KAN_VARSLES',
            'kontaktinformasjon': {
                'mobiltelefonnummer_oppdatert': '2015-03-11T20: 01: 18.000+01: 00',
                'mobiltelefonnummer_sist_verifisert': '2017-11-07T10: 32: 11.000+01: 00',
                'mobiltelefonnummer': '+4799999999',
                'epostadresse_oppdatert': None,
                'epostadresse_sist_verifisert': None,
                'epostadresse': None,
            },
            'spraak': None,
            'spraak_oppdatert': None,
        },
        {
            'personidentifikator': '27129323456',
            'reservasjon': 'NEI',
            'status': 'AKTIV',
            'varslingsstatus': 'KAN_VARSLES',
            'kontaktinformasjon': {
                'mobiltelefonnummer_oppdatert': '2015-03-11T20: 00: 53.000+01: 00',
                'mobiltelefonnummer_sist_verifisert': '2017-11-07T10: 34: 27.000+01: 00',
                'mobiltelefonnummer': '+4799999999',
                'epostadresse_oppdatert': None,
                'epostadresse_sist_verifisert': None,
                'epostadresse': None,
            },
            'spraak': None,
            'spraak_oppdatert': None,
        },
        {
            'personidentifikator': '27129323375',
            'reservasjon': 'NEI',
            'status': 'AKTIV',
            'varslingsstatus': 'KAN_VARSLES',
            'kontaktinformasjon': {
                'mobiltelefonnummer_oppdatert': None,
                'mobiltelefonnummer_sist_verifisert': None,
                'mobiltelefonnummer': None,
                'epostadresse_oppdatert': '2017-11-07T15: 43: 14.000+01: 00',
                'epostadresse_sist_verifisert': '2017-11-07T15: 43: 14.000+01: 00',
                'epostadresse': '27129323375-test@minid.norge.no',
            },
            'spraak': None,
            'spraak_oppdatert': None,
        },
        {
            'personidentifikator': '27129323294',
            'reservasjon': 'NEI',
            'status': 'AKTIV',
            'varslingsstatus': 'KAN_VARSLES',
            'kontaktinformasjon': {
                'mobiltelefonnummer_oppdatert': None,
                'mobiltelefonnummer_sist_verifisert': None,
                'mobiltelefonnummer': None,
                'epostadresse_oppdatert': '2017-11-07T15: 45: 24.000+01: 00',
                'epostadresse_sist_verifisert': '2017-11-07T15: 45: 24.000+01: 00',
                'epostadresse': '27129323294-test@minid.norge.no',
            },
            'spraak': None,
            'spraak_oppdatert': None,
        },
        {
            'personidentifikator': '24079412372',
            'reservasjon': 'NEI',
            'status': 'AKTIV',
            'varslingsstatus': 'KAN_VARSLES',
            'kontaktinformasjon': {
                'mobiltelefonnummer_oppdatert': '2017-11-07T10: 56: 35.000+01: 00',
                'mobiltelefonnummer_sist_verifisert': None,
                'mobiltelefonnummer': '99999999',
                'epostadresse_oppdatert': '2017-11-07T10: 50: 03.000+01: 00',
                'epostadresse_sist_verifisert': '2017-11-07T10: 50: 15.000+01: 00',
                'epostadresse': '24079412372-test@minid.norge.no',
            },
            'spraak': None,
            'spraak_oppdatert': None,
        },
        {
            'personidentifikator': '11089499889',
            'reservasjon': 'NEI',
            'status': 'AKTIV',
            'varslingsstatus': 'KAN_VARSLES',
            'kontaktinformasjon': {
                'mobiltelefonnummer_oppdatert': '2017-11-07T11: 36: 48.000+01: 00',
                'mobiltelefonnummer_sist_verifisert': '2017-11-07T11: 36: 48.000+01: 00',
                'mobiltelefonnummer': '+4799999999',
                'epostadresse_oppdatert': '2017-11-07T11: 38: 44.000+01: 00',
                'epostadresse_sist_verifisert': '2017-11-07T11: 38: 44.000+01: 00',
                'epostadresse': '11089499889-test@minid.norge.no',
            },
            'spraak': None,
            'spraak_oppdatert': None,
        },
        {
            'personidentifikator': '24079412291',
            'reservasjon': 'JA',
            'status': 'AKTIV',
            'varslingsstatus': 'KAN_IKKE_VARSLES',
            'kontaktinformasjon': {
                'mobiltelefonnummer_oppdatert': None,
                'mobiltelefonnummer_sist_verifisert': None,
                'mobiltelefonnummer': None,
                'epostadresse_oppdatert': None,
                'epostadresse_sist_verifisert': None,
                'epostadresse': None,
            },
            'spraak': None,
            'spraak_oppdatert': None,
        },
        {
            'personidentifikator': '29129319060',
            'reservasjon': 'NEI',
            'status': 'AKTIV',
            'varslingsstatus': 'KAN_VARSLES',
            'kontaktinformasjon': {
                'mobiltelefonnummer_oppdatert': '2015-03-11T19: 59: 15+01',
                'mobiltelefonnummer_sist_verifisert': '2020-11-12T10: 41: 10+01',
                'mobiltelefonnummer': '+4799999999',
                'epostadresse_oppdatert': '2015-03-11T19: 59: 15+01',
                'epostadresse_sist_verifisert': '2020-11-12T10: 41: 10+01',
                'epostadresse': '29129319060-test@minid.norge.no',
            },
            'spraak': 'nn',
            'spraak_oppdatert': '2020-11-12T10: 41: 20+01',
        },
        {
            'personidentifikator': '29129318943',
            'reservasjon': 'NEI',
            'status': 'AKTIV',
            'varslingsstatus': 'KAN_VARSLES',
            'kontaktinformasjon': {
                'mobiltelefonnummer_oppdatert': '2015-03-11T20: 00: 39+01',
                'mobiltelefonnummer_sist_verifisert': '2020-11-12T11: 00: 53+01',
                'mobiltelefonnummer': '+4799999999',
                'epostadresse_oppdatert': '2015-03-11T20: 00: 39+01',
                'epostadresse_sist_verifisert': '2020-11-12T11: 00: 53+01',
                'epostadresse': '29129318943-test@minid.norge.no',
            },
            'spraak': 'nb',
            'spraak_oppdatert': '2020-11-12T11: 00: 58+01',
        },
        {
            'personidentifikator': '29129318862',
            'reservasjon': 'NEI',
            'status': 'AKTIV',
            'varslingsstatus': 'KAN_VARSLES',
            'kontaktinformasjon': {
                'mobiltelefonnummer_oppdatert': '2015-03-11T20: 01: 07+01',
                'mobiltelefonnummer_sist_verifisert': '2020-11-12T11: 08: 06+01',
                'mobiltelefonnummer': '+4799999999',
                'epostadresse_oppdatert': '2015-03-11T20: 01: 07+01',
                'epostadresse_sist_verifisert': '2020-11-12T11: 08: 06+01',
                'epostadresse': '29129318862-test@minid.norge.no',
            },
            'spraak': 'en',
            'spraak_oppdatert': '2020-11-12T11: 08: 29+01',
        },
        {
            'personidentifikator': '29129318781',
            'reservasjon': 'NEI',
            'status': 'AKTIV',
            'varslingsstatus': 'KAN_VARSLES',
            'kontaktinformasjon': {
                'mobiltelefonnummer_oppdatert': '2015-03-11T19: 54: 55+01',
                'mobiltelefonnummer_sist_verifisert': '2020-11-12T11: 14: 54+01',
                'mobiltelefonnummer': '+4799999999',
                'epostadresse_oppdatert': '2015-03-11T19: 54: 55+01',
                'epostadresse_sist_verifisert': '2020-11-12T11: 14: 54+01',
                'epostadresse': '29129318781-test@minid.norge.no',
            },
            'spraak': 'se',
            'spraak_oppdatert': '2020-11-12T11: 16: 19+01',
        },
    ]
}


krr_test_persons_only_nnids = [
    p['personidentifikator'] for p in krr_test_persons['personer']
]
