steps:
- name: 'gcr.io/cloud-builders/docker'
  dir: $_DIR
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA'
    - '-t'
    - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:terraform-$_TERRAFORM_VERSION'
    - '-t'
    - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:latest'
    - '.'
    - '--build-arg'
    - 'project_id=$PROJECT_ID'
    - '--build-arg'
    - 'TERRAFORM_VERSION=$_TERRAFORM_VERSION'
images:
- 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:terraform-$_TERRAFORM_VERSION'
- 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:latest'
