  steps:
  - name: python:3.10  # Downloads innbyggerkontakt from artifact registry
    entrypoint: pip
    id: download_ikutils_from_artifacts
    args:
    - 'download'
    - '--no-deps'
    - '--extra-index-url'
    - 'https://europe-west3-python.pkg.dev/$PROJECT_ID/ik-python-repo/simple'
    - '-d'
    - '/workspace/$_DIR/packages/'
    - 'innbyggerkontakt'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA', '.']
    dir: $_DIR

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA']

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image=gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA
      - --region=$_LOCATION
      - --platform=managed
