steps:
  - name: 'gcr.io/$PROJECT_ID/deployment:terraform-$_TERRAFORM_VERSION'
    dir: $_DIR
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        pip3 install -r requirements.txt
        terraform init -reconfigure -upgrade -backend-config=$PROJECT_ID.tfbackend
        terraform plan -lock=false -var 'project_id=$PROJECT_ID'

timeout: 1800s
